# Docker compose file for testnets

version: "3"

services:
    # main network
    ethereum:
        image: ethereum/client-go
        restart: always
        command:
            - "--syncmode=full"
            - "--rpc"
            - "--rpcaddr=0.0.0.0"
            - "--rpcvhosts='*.ethco.de'"
            - "--cache=2048"
            - "--rpcapi=eth,web3,personal,debug"
            - "--gcmode=archive"
        ports:
            - 8545:8545
            - 30302:30303
        volumes: 
            - /storage/ethereum_data:/root/.ethereum/
    # main network syncmode light
    ethereum-light:
        image: ethereum/client-go
        restart: always
        command:
            - "--syncmode=light"
            - "--rpc"
            - "--rpcaddr=0.0.0.0"
            - "--rpcvhosts='*.ethco.de'"
            - "--cache=2048"
            - "--rpcapi=eth,web3,personal,debug"
            - "--gcmode=archive"
        ports:
            - 8546:8545
            - 30302:30303
        volumes: 
            - /storage/ethereum_data:/root/.ethereum/geth_light
    # Goerli Test Network
    goerli:
        image: ethereum/client-go
        restart: always
        command:
            - "--syncmode=full"
            - "--goerli"
            - "--rpc"
            - "--rpcaddr=0.0.0.0"
            - "--rpcvhosts='*.ethco.de'"
            - "--cache=2048"
            - "--rpcapi=eth,web3,personal,debug"
            - "--gcmode=archive"
        ports:
            - 7545:8545
            - 30303:30303
        volumes: 
            - /storage/ethereum_data:/root/.ethereum/

    # Ropsten Test Network
    ropsten:
        image: ethereum/client-go
        restart: always
        command:
            - "--syncmode=full"
            - "--testnet"
            - "--rpc"
            - "--rpcaddr=0.0.0.0"
            - "--rpcvhosts='*.ethco.de'"
            - "--cache=2048"
            - "--rpcapi=eth,web3,personal,debug"
            - "--gcmode=archive"
        ports:
            - 7546:8545
            - 30304:30303
        volumes: 
            - /storage/ethereum_data:/root/.ethereum/

    # Rinkeby Test Network
    rinkeby:
        image: ethereum/client-go
        restart: always
        command:
            - "--syncmode=full"
            - "--rinkeby"
            - "--rpc"
            - "--rpcaddr=0.0.0.0"
            - "--rpcvhosts='*.ethco.de'"
            - "--cache=2048"
            - "--rpcapi=eth,web3,personal,debug"
            - "--gcmode=archive"
        ports:
            - 7547:8545
            - 30305:30303
        volumes: 
            - /storage/ethereum_data:/root/.ethereum/

    # Ethereum 2.0 Test Network Prysm Sapphire
    # prysm-sapphire:
    #     image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    #     restart: always
    #     command:
    #         - "--datadir=/data/.ethereum"
    #     ports:
    #         - 7548:4000
    #         - 13000:13000
    #     volumes:
    #         - /storage/ethereum_data:/data/
