version: "3.7"
## Traefik reverse proxy
services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0.5
    restart: always
    command:
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch"
    ports:
      - "80:80"
      - "443:443"
      - "50051:50051"
      - "50052:50052"
      - "50053:50053"
    networks:
      - inbound
      - traefik
    links:
      - prometheus
      - grafana
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./logs:/var/log/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.api.service=api@internal"
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=le
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$LAHn3.vc$$47mKL7WmzOQWwJ2OjND46/"

  ## Remix Tests API
  remix-tests-api:
    container_name: remix-tests-api
    restart: always
    build: remix-tests-api/
    networks:
      - inbound
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remix-tests-api.rule=Host(`${RT_API_HOST}`)"
      - "traefik.http.routers.remix-tests-api.entrypoints=rt-port"
      - "traefik.http.services.remix-tests-api.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.remix-tests-api.loadbalancer.server.port=50051"
  
  ## Remix Debug API
  remix-debug-api:
    container_name: remix-debug-api
    restart: always
    build: remix-debug-api/
    networks:
      - inbound
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remix-debug-api.rule=Host(`${RD_API_HOST}`)"
      - "traefik.http.routers.remix-debug-api.entrypoints=rd-port"
      - "traefik.http.services.remix-debug-api.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.remix-debug-api.loadbalancer.server.port=50052"

  # ## client call api
  client-call-api:
    container_name: client-call-api
    restart: always
    build: client-call-api/
    networks:
      - inbound
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-call-api.rule=Host(`${CC_API_HOST}`)"
      - "traefik.http.routers.client-call-api.entrypoints=cc-port"
      - "traefik.http.services.client-call-api.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.client-call-api.loadbalancer.server.port=50053"

  ## ganache
  ganache:
    image: trufflesuite/ganache-cli
    restart: always
    networks:
      - inbound
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ganache-api.rule=Host(`ganache.localhost`)"
      - "traefik.http.routers.ganache-api.entrypoints=ganache-port"
      - "traefik.http.services.ganache-api.loadbalancer.server.port=8545"

  ## Prometheus
  prometheus:
    image: prom/prometheus
    user: "root:root"
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - inbound
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`${PROM_HOST}`)"
      - "traefik.http.routers.prometheus.entrypoints=prm-port"
      - "traefik.docker.network=inbound"
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=le
      - "traefik.prometheus.auth.basicauth.users=admin:$$apr1$$LAHn3.vc$$47mKL7WmzOQWwJ2OjND46/"


  # Node Exporter
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks: 
      - inbound
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`node.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=node"
      - "traefik.docker.network=inbound"

  ## Grafana
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    links: 
      - prometheus
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - inbound
    env_file:
      - ./grafana/config.monitoring
    user: "root:root"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOST}`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.docker.network=inbound"

networks:
  traefik:
    driver: overlay
    name: traefik
  inbound:
    driver: overlay
    name: inbound
  # default:
  #   external:
  #     name: inbound

volumes:
    prometheus_data: {}
    grafana_data: {}