version: "3.7"
## Traefik reverse proxy
services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      - "traefik.enable=true"
  ## Remix Tests API
  remix-tests-api:
    container_name: remix-tests-api
    restart: always
    build: remix-tests-api/
    ports:
      - "50051:50051"
    labels:
      - "traefik.http.routers.remix-tests-api.rule=Host(`${RT_API_HOST}`)"