[log]
  level = "debug"
[entryPoints]
  [entryPoints.metrics]
    address = ":8082"
  [entryPoints.rt-port]
    address = ":50051"
[api]
  dashboard = true
  insecure = true
  debug = true
[providers]
  [providers.docker]
[accessLog]
[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true
