defaultEntryPoints = ["web", "web-secure"]
[log]
  level = "DEBUG"
[entryPoints]

  [entryPoints.rt-port]
    address = ":50051"
  [entryPoints.rd-port]
    address = ":50052"
  [entryPoints.cc-port]
    address = ":50053"
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
[http.routers]
  [http.routers.web-secure]
    entryPoints=["web-secure"]
    [http.routers.web-secure.tls]


[api]
  dashboard = true
  insecure = false
  debug = true
[providers]
  [providers.docker]
[accessLog]
  filePath = "/var/log/traefik.log"
[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true
[certificatesResolvers]
  [certificatesResolvers.le]
    [certificatesResolvers.le.acme]
      email = "0mkar@protonmail.com"
      storage = "acme.json"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
    [certificatesResolvers.le.acme.tlsChallenge]
