[log]
  level = "DEBUG"
[entryPoints]
  [entryPoints.rt-port]
    address = ":50051"
  [entryPoints.rd-port]
    address = ":50052"
<<<<<<< HEAD
  [entryPoints.ganache-port]
    address = ":8545"
  [entryPoints.cc-port]
    address = ":50053"
=======
  [entryPoints.web]
      address = ":80"
>>>>>>> 78af6b10da10d563421d9e1c8c1d642acd929fa3
[api]
  dashboard = true
  insecure = false
  debug = true
[providers]
  [providers.docker]
[accessLog]
  filePath = "/var/log/traefik.log"
[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true