[log]
  level = "debug"
[entryPoints]
  [entryPoints.rt-port]
    address = ":50051"
<<<<<<< HEAD
  [entryPoints.graf]
      address = ":3000"
  [entryPoints.prome]
      address = ":9090"
=======
  [entryPoints.rd-port]
    address = ":50052"
>>>>>>> master
[api]
  dashboard = true
  insecure = true
  debug = true
[providers]
  [providers.docker]
[accessLog]
  filePath = "/var/log/traefik.log"
[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true
