defaultEntryPoints = ["http", "https"]
[log]
  level = "DEBUG"
[entryPoints]
  [entryPoints.rt-port]
    address = ":50051"
  [entryPoints.rd-port]
    address = ":50052"
  [entryPoints.cc-port]
    address = ":50053"
  [entryPoints.ganache-port]
    address = ":8545"
  [entryPoints.prm-port]
    address = ":9090"
  [entryPoints.node]
    address = ":9100"
  [entryPoints.web]
      address = ":80"
  [entryPoints.web-secure]
    address = ":443"
[api]
  dashboard = true
  insecure = false
  debug = true
[providers]
  [providers.docker]
[accessLog]
  filePath = "/var/log/traefik.log"
[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true
[acme]
email = "ayanb1999@gmail.com"
entryPoint = "https"
storage = "./acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
onHostRule = true
  [acme.dnsChallenge]
  provider = "aws"
  delayBeforeCheck = 0
  [[acme.domains]]
   main = "ethcode.dev"
  [[acme.domains]]
   main = "*.ethcode.dev"