apiVersion: v1
kind: Service
metadata:
  name: ethereum-grpc-api-ip-svc
spec:
  type: NodePort
  selector:
    backend: ethereum-grpc-api
  ports:
    - name: ethereum-grpc-api
      port: 50054
      targetPort: 50054