apiVersion: v1
kind: Service
metadata:
  name: remix-tests-api-cluster-ip-svc
spec:
  type: NodePort
  selector:
    backend: remix-tests-api
  ports:
    - name: remix-tests-api
      port: 50051
      targetPort: 50051
      nodePort: 31515