apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: monitoring
  name: monitoring-pv-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50M