global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'remix-tests-api'
rule_files:
  - 'alert.rules'
scrape_configs:
  # prometheus scrape config
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  # remix-tests-api scrape config
  - job_name: 'remix-tests-api'
    scrape_interval: 5s
    static_configs:
         - targets: ['remix-tests-api:50051']
  # remix-debug-api scrape config
  - job_name: 'remix-debug-api'
    scrape_interval: 5s
    static_configs:
         - targets: ['remix-debug-api:50052']
  # Node Exporter
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
         - targets: ['node-exporter:9100']
  
  # traefik scrape config
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['traefik:8080']
    dns_sd_configs:
    - names:
      - 'tasks.traefik'
      type: 'A'
      port: 8080
