apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: auth-api
  template:
    metadata:
      labels:
        backend: auth-api
    spec:
      restartPolicy: Always
      containers:
        - name: auth-api
          image: gcr.io/eth-devtools-api-dev/auth-api:0.1
          ports:
            - containerPort: 4040