apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tls
  namespace: default
spec:
  entryPoints:
    - web-secure

  routes:
    - match: Host(`traefik.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: basic-auth
      services:
        - name: api@internal
          kind: TraefikService
          port: 8080
    - match: Host(`auth.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: auth-api-cluster-ip-svc
          port: 4040
    - match: Host(`etherscanner.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: etherscanner-backend-cluster-svc
          port: 4545
    - match: Host(`grafana.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: grafana-cluster-ip-svc
          port: 3000
    - match: Host(`prometheus.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: basic-auth
      services:
        - name: prometheus-cluster-ip-svc
          port: 9090
          # scheme: https

  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-web
  namespace: default
spec:
  entryPoints:
    - web

  routes:
    - match: Host(`traefik.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: https-redirectscheme
      services:
        - name: api@internal
          kind: TraefikService
          port: 8080
    - match: Host(`auth.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: auth-api-cluster-ip-svc
          port: 4040
      middlewares:
        - name: https-redirectscheme
    - match: Host(`etherscanner.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: etherscanner-backend-cluster-svc
          port: 4545
      middlewares:
        - name: https-redirectscheme
    - match: Host(`grafana.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: grafana-cluster-ip-svc
          port: 3000
      middlewares:
        - name: https-redirectscheme
    - match: Host(`prometheus.ethco.de`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: basic-auth
        - name: https-redirectscheme
      services:
        - name: prometheus-cluster-ip-svc
          port: 9090
