{
 "title": "Traefik2",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "backend", "query": "label_values(backend)" },
   { "name": "entrypoint", "query": "label_values(entrypoint)" }
  ]
 },
 "panels": [
  {
   "title": "Total requests over 5min $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "Total requests $backend" }
   ]
  },
  {
   "title": "Http Request duration count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_http_request_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_config_last_reload_success_timestamp_seconds",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 1, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_failures_total"
    }
   ]
  },
  {
   "title": "Go Runtime Duration(seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds" }
   ]
  },
  {
   "title": "Go Gc CPU Fraction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_gc_cpu_fraction" }
   ]
  },
  {
   "title": "Cpu Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Go Memory Usage",
   "type": "graph",
   "description": "how much Go is using from that. A large difference between these two could indicate spiky memory usage, or fragmentation issues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "he amount of memory the Prometheus process is using from the kernel,",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Go Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_threads" }
   ]
  },
  { "title": "$backend stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } }
 ]
}