apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: grafana
  template:
    metadata:
      labels:
        backend: grafana
    spec:
      restartPolicy: Always
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: monitoring-pv-claim
            # readOnly: false
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: monitoring-pv-claim
          persistentVolumeClaim:
            claimName: monitoring-pv-claim
        - name: grafana-datasources
          configMap:
              name: grafana-datasources
