apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: prometheus
  template:
    metadata:
      labels:
        backend: prometheus
    spec:
      restartPolicy: Always
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090