apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: traefik
  template:
    metadata:
      labels:
        backend: traefik
    spec:
      containers:
        - name: traefik
          image: traefik:v2.0.5
          ports:
            - containerPort: 8080
      restartPolicy: Always