apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`trf.ethco.de`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
  - match: Host(`graf.ethco.de`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: grafana-cluster-ip-svc
      port: 3000