apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: traefik
  labels:
    backend: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      backend: traefik
  template:
    metadata:
      labels:
        backend: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0.5
          args:
            - "--entrypoints.https.address=:443"
            - "--certificatesresolvers.traefik.acme.httpchallenge=true"
            - "--certificatesresolvers.traefik.acme.httpchallenge.entrypoint=web-secure"
            - "--certificatesresolvers.traefik.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
            - "--certificatesresolvers.traefik.acme.email=0mkar@protonmail.com"
            - "--certificatesresolvers.traefik.acme.storage=/acme.json"
          ports:
            - name: web
              containerPort: 80
            - name: admin
              containerPort: 8080
