kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik
  labels:
    backend: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      backend: traefik
  template:
    metadata:
      labels:
        backend: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.1
          args:
            - --log.level=DEBUG
            - --api
            - --api.insecure
            - --entrypoints.web.address=:80
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 80
            - name: admin
              containerPort: 8080