apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: web-secure
      port: 443
  selector:
    app: traefik
  type: LoadBalancer