# Declaring the user list
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-auth
spec:
  basicAuth:
    secret: authsecret

---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default

data:
  users: YWRtaW46JCRhcHIxJCRMQUhuMy52YyQkNDdtS0w3V216T1FXd0oyT2pORDQ2Lw==