apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: web-secure
      port: 443
    - protocol: TCP
      name: cc-port
      port: 50053
    - protocol: TCP
      name: rd-port
      port: 50052
    - protocol: TCP
      name: rt-port
      port: 50051
  selector:
    app: traefik
  type: LoadBalancer