apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'remix-tests-api'
    rule_files:
      - 'alert.rules'
    scrape_configs:
      # prometheus scrape config
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      # remix-tests-api scrape config
      - job_name: 'remix-tests-api'
        scrape_interval: 5s
        static_configs:
             - targets: ['rt.ethco.de:50051']
      # remix-debug-api scrape config
      - job_name: 'remix-debug-api'
        scrape_interval: 5s
        static_configs:
             - targets: ['rd.ethco.de:50052']
      # Node Exporter
      - job_name: 'node-exporter'
        scrape_interval: 5s
        static_configs:
          - targets: ['node-exporter-cluster-ip-svc:9100']
      
      # traefik scrape config
      - job_name: 'traefik'
        scrape_interval: 5s
        static_configs:
          - targets: ['trf.ethco.de']
        dns_sd_configs:
        - names:
          - 'tasks.traefik'
          type: 'A'
          port: 8080
    
