# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethereum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethereum.proto',
  package='protoeth',
  syntax='proto3',
  serialized_options=_b('Z\010protoeth'),
  serialized_pb=_b('\n\x0e\x65thereum.proto\x12\x08protoeth\"7\n\x13\x43lientCallInterface\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"I\n\x11\x43lientCallRequest\x12\x34\n\rcallInterface\x18\x01 \x01(\x0b\x32\x1d.protoeth.ClientCallInterface\"$\n\x12\x43lientCallResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2_\n\x0fProtoEthService\x12L\n\x0bGetAccounts\x12\x1b.protoeth.ClientCallRequest\x1a\x1c.protoeth.ClientCallResponse\"\x00\x30\x01\x42\nZ\x08protoethb\x06proto3')
)




_CLIENTCALLINTERFACE = _descriptor.Descriptor(
  name='ClientCallInterface',
  full_name='protoeth.ClientCallInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='protoeth.ClientCallInterface.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='protoeth.ClientCallInterface.payload', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=83,
)


_CLIENTCALLREQUEST = _descriptor.Descriptor(
  name='ClientCallRequest',
  full_name='protoeth.ClientCallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='callInterface', full_name='protoeth.ClientCallRequest.callInterface', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=158,
)


_CLIENTCALLRESPONSE = _descriptor.Descriptor(
  name='ClientCallResponse',
  full_name='protoeth.ClientCallResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='protoeth.ClientCallResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=196,
)

_CLIENTCALLREQUEST.fields_by_name['callInterface'].message_type = _CLIENTCALLINTERFACE
DESCRIPTOR.message_types_by_name['ClientCallInterface'] = _CLIENTCALLINTERFACE
DESCRIPTOR.message_types_by_name['ClientCallRequest'] = _CLIENTCALLREQUEST
DESCRIPTOR.message_types_by_name['ClientCallResponse'] = _CLIENTCALLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientCallInterface = _reflection.GeneratedProtocolMessageType('ClientCallInterface', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCALLINTERFACE,
  '__module__' : 'ethereum_pb2'
  # @@protoc_insertion_point(class_scope:protoeth.ClientCallInterface)
  })
_sym_db.RegisterMessage(ClientCallInterface)

ClientCallRequest = _reflection.GeneratedProtocolMessageType('ClientCallRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCALLREQUEST,
  '__module__' : 'ethereum_pb2'
  # @@protoc_insertion_point(class_scope:protoeth.ClientCallRequest)
  })
_sym_db.RegisterMessage(ClientCallRequest)

ClientCallResponse = _reflection.GeneratedProtocolMessageType('ClientCallResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCALLRESPONSE,
  '__module__' : 'ethereum_pb2'
  # @@protoc_insertion_point(class_scope:protoeth.ClientCallResponse)
  })
_sym_db.RegisterMessage(ClientCallResponse)


DESCRIPTOR._options = None

_PROTOETHSERVICE = _descriptor.ServiceDescriptor(
  name='ProtoEthService',
  full_name='protoeth.ProtoEthService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=198,
  serialized_end=293,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAccounts',
    full_name='protoeth.ProtoEthService.GetAccounts',
    index=0,
    containing_service=None,
    input_type=_CLIENTCALLREQUEST,
    output_type=_CLIENTCALLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROTOETHSERVICE)

DESCRIPTOR.services_by_name['ProtoEthService'] = _PROTOETHSERVICE

# @@protoc_insertion_point(module_scope)
