# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ethereum_pb2 as ethereum__pb2


class ProtoEthServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAccounts = channel.unary_unary(
        '/protoeth.ProtoEthService/GetAccounts',
        request_serializer=ethereum__pb2.GetAccountsReq.SerializeToString,
        response_deserializer=ethereum__pb2.GetAccountsResp.FromString,
        )
    self.GetBalance = channel.unary_unary(
        '/protoeth.ProtoEthService/GetBalance',
        request_serializer=ethereum__pb2.GetBalanceReq.SerializeToString,
        response_deserializer=ethereum__pb2.GetBalanceResp.FromString,
        )
    self.GetTransaction = channel.unary_unary(
        '/protoeth.ProtoEthService/GetTransaction',
        request_serializer=ethereum__pb2.TxHash.SerializeToString,
        response_deserializer=ethereum__pb2.TransactionInfo.FromString,
        )
    self.SendRawTransactions = channel.unary_stream(
        '/protoeth.ProtoEthService/SendRawTransactions',
        request_serializer=ethereum__pb2.RawTxRequest.SerializeToString,
        response_deserializer=ethereum__pb2.TxResponse.FromString,
        )
    self.GetTransactionReceipt = channel.unary_unary(
        '/protoeth.ProtoEthService/GetTransactionReceipt',
        request_serializer=ethereum__pb2.TxHash.SerializeToString,
        response_deserializer=ethereum__pb2.TxReceipt.FromString,
        )


class ProtoEthServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAccounts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendRawTransactions(self, request, context):
    """eth_sendRawTransaction should have simple requests but stream of responses
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionReceipt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProtoEthServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAccounts': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccounts,
          request_deserializer=ethereum__pb2.GetAccountsReq.FromString,
          response_serializer=ethereum__pb2.GetAccountsResp.SerializeToString,
      ),
      'GetBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetBalance,
          request_deserializer=ethereum__pb2.GetBalanceReq.FromString,
          response_serializer=ethereum__pb2.GetBalanceResp.SerializeToString,
      ),
      'GetTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransaction,
          request_deserializer=ethereum__pb2.TxHash.FromString,
          response_serializer=ethereum__pb2.TransactionInfo.SerializeToString,
      ),
      'SendRawTransactions': grpc.unary_stream_rpc_method_handler(
          servicer.SendRawTransactions,
          request_deserializer=ethereum__pb2.RawTxRequest.FromString,
          response_serializer=ethereum__pb2.TxResponse.SerializeToString,
      ),
      'GetTransactionReceipt': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionReceipt,
          request_deserializer=ethereum__pb2.TxHash.FromString,
          response_serializer=ethereum__pb2.TxReceipt.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protoeth.ProtoEthService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
