apiVersion: v1
kind: Service
metadata:
  name: monitoring-cluster-ip-svc
spec:
  type: ClusterIP
  selector:
    backend: monitoring
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: node-exporter
      port: 9100
      targetPort: 9100