apiVersion: v1
kind: Service
metadata:
  name: node-exporter-cluster-ip-svc
spec:
  type: NodePort
  selector:
    backend: node-exporter
  ports:
    - name: node-exporter
      port: 9100
      targetPort: 9100
      targetPort: 31514