networks:
  ganache:
    id: 0
    # url: "http://ganache:8545"
    url: "http://127.0.0.1:8545"
  main:
    id: 1
    url: "http://networks.ethco.de/light"
  ropsten:
    id: 3
    url: "http://networks.ethco.de/ropsten"
  rinkeby:
    id: 4
    url: "http://networks.ethco.de/rinkeby"
  görli:
    id: 5
    url: "http://networks.ethco.de/goerli"
